### ISSUE TITLE
TypeScript should be in a strict mode

### ISSUE THREAD

**Issue by ShepelievD** [mikearnaldi/next-flexible-routes#4]
## Description:

TS should be in a script mode for safety. Benefits of strict mode: [https://www.geeksforgeeks.org/strict-mode-javascript/](https://www.geeksforgeeks.org/strict-mode-javascript/)

## Acceptance Criteria
- [x] Errors & warnings related to strict mode should be fixed

**Comment by mikearnaldi** [comment]
@ShepelievD but should be done

**Comment by mikearnaldi** [comment]
https://github.com/mikearnaldi/next-flexible-routes/commit/b1fff154ef94ee8368d22ee0a80dfe022de58510
