### ISSUE TITLE
Eliminate magical var names

### ISSUE THREAD

**Issue by ShepelievD** [mikearnaldi/next-flexible-routes#5]
## Description:
We should have an easy reading generic types/args of the functions.

Example of an issue:
https://github.com/mikearnaldi/next-flexible-routes/blob/master/lib/types/RouteQ.ts#L20

On that line we can see `RouteQSpec<Q extends t.Props, QO extends t.Props>`. It is not clear what `Q` or `QO` means.

## Acceptance Criteria:
- [x] Every type/argument should be "talkative"

**Comment by mikearnaldi** [comment]
@ShepelievD should be addressed

**Comment by ShepelievD** [comment]
@mikearnaldi :)

Found more:
- [ ] https://github.com/mikearnaldi/next-flexible-routes/blob/master/lib/api.ts#L68
- [ ] https://github.com/mikearnaldi/next-flexible-routes/blob/master/lib/api.ts#L74
- [ ] https://github.com/mikearnaldi/next-flexible-routes/blob/master/lib/api.ts#L122
- [ ] https://github.com/mikearnaldi/next-flexible-routes/blob/master/lib/api.ts#L125
- [ ] https://github.com/mikearnaldi/next-flexible-routes/blob/master/lib/api.ts#L166
- [ ] https://github.com/mikearnaldi/next-flexible-routes/blob/master/lib/api.ts#L169
- [ ] https://github.com/mikearnaldi/next-flexible-routes/blob/master/lib/codecs.ts#L6
- [ ] https://github.com/mikearnaldi/next-flexible-routes/blob/master/lib/codecs.ts#L16
- [ ] https://github.com/mikearnaldi/next-flexible-routes/blob/master/lib/codecs.ts#L24
- [ ] https://github.com/mikearnaldi/next-flexible-routes/blob/master/lib/codecs.ts#L25
- [ ] https://github.com/mikearnaldi/next-flexible-routes/blob/master/lib/codecs.ts#L30
- [ ] https://github.com/mikearnaldi/next-flexible-routes/blob/master/lib/extended.iots.ts#L4

**Comment by mikearnaldi** [comment]
@ShepelievD pls send a PR

**Comment by ShepelievD** [comment]
@mikearnaldi unassigned myself, please fix names

**Comment by mikearnaldi** [comment]
https://github.com/mikearnaldi/next-flexible-routes/commit/c1efe66138296a4425610e3d9570ef7a217a5dae

**Comment by mikearnaldi** [comment]
https://github.com/mikearnaldi/next-flexible-routes/commit/1a0c2ce44032d5976fdf75e7e0f9abcb31492362
